'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SegTest.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureCardboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureCardboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TextureVintage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TextureVintage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLBack&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 285.242,76.6486L 76.6696,284.891C 65.2469,296.315 53.6603,307.903 53.4963,330.75L 53.4963,330.75C 53.3336,352.13 62.4736,363.39 76.6696,377.59L 285.242,586.159C 296.8 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLBack() As String
            Get
                Return ResourceManager.GetString("XAMLBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLBackBack&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 539.164,36.6488L 338.101,237.383L 338.101,59.8235C 338.101,36.6488 314.928,13.4728 291.753,13.4728L 291.753,13.4728C 268.579,13.4728 256.992,25.0621 245.404,36.64 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLBackBack() As String
            Get
                Return ResourceManager.GetString("XAMLBackBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLBackBackGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 539.164,36.6489L 338.101,237.383L 338.101,59.8235C 338.101,36.6489 314.928,13.4728 291.753,13.4728L 291.753,13.4728C 268.579,13.4728 256.992,25.0622 245.404,3 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLBackBackGray() As String
            Get
                Return ResourceManager.GetString("XAMLBackBackGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLBackGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 285.242,76.6486L 76.6696,284.891C 65.2469,296.315 53.6603,307.903 53.4963,330.75L 53.4963,330.75C 53.3336,352.13 62.4736,363.39 76.6696,377.59L 285.242,586.159C 2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLBackGray() As String
            Get
                Return ResourceManager.GetString("XAMLBackGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLConfiguration&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 360.341,212.179C 353.992,212.179 350.815,216.94 349.229,223.291L 334.943,305.835C 307.956,312.185 282.557,323.297 260.333,337.584L 190.489,288.373C 185.727,2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLConfiguration() As String
            Get
                Return ResourceManager.GetString("XAMLConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLConfigurationGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 360.341,212.179C 353.992,212.179 350.815,216.94 349.229,223.291L 334.943,305.835C 307.956,312.185 282.557,323.297 260.333,337.584L 190.489,288.373C 185.7 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLConfigurationGray() As String
            Get
                Return ResourceManager.GetString("XAMLConfigurationGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLExit&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 196.897,397.633C 196.897,599.273 360.359,762.736 562,762.736L 562,762.736C 763.64,762.736 927.103,599.273 927.103,397.633L 927.103,397.633C 927.103,195.992 763.64,32. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLExit() As String
            Get
                Return ResourceManager.GetString("XAMLExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLForward&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 53.3341,99.8234L 53.3341,562.985C 53.3341,586.159 76.5088,609.334 99.6821,609.334L 99.6821,609.334C 122.855,609.334 134.443,597.746 146.03,586.159L 354.601,377.59C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLForward() As String
            Get
                Return ResourceManager.GetString("XAMLForward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLForwardForward&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 307.093,59.8232L 307.093,237.383L 106.031,36.6486C 94.4439,25.0619 82.8572,13.4725 59.6825,13.4725L 59.6825,13.4725C 36.5092,13.4725 13.3345,36.6486 13.3345 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLForwardForward() As String
            Get
                Return ResourceManager.GetString("XAMLForwardForward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLForwardForwardGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 307.093,59.8232L 307.093,237.383L 106.031,36.6486C 94.4439,25.0619 82.8572,13.4725 59.6825,13.4725L 59.6825,13.4725C 36.5092,13.4725 13.3345,36.6486 13. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLForwardForwardGray() As String
            Get
                Return ResourceManager.GetString("XAMLForwardForwardGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLForwardGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 53.3341,99.8234L 53.3341,562.985C 53.3341,586.159 76.5088,609.334 99.6821,609.334L 99.6821,609.334C 122.855,609.334 134.443,597.746 146.03,586.159L 354.601,377 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLForwardGray() As String
            Get
                Return ResourceManager.GetString("XAMLForwardGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLGrabCut&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 398,300.225C 542.655,300.225 659.921,417.492 659.921,562.146C 659.921,706.802 542.655,824.069 398,824.069C 253.345,824.069 136.079,706.802 136.079,562.146C 136.079 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLGrabCut() As String
            Get
                Return ResourceManager.GetString("XAMLGrabCut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLGrabCutGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 398,300.225C 542.655,300.225 659.921,417.492 659.921,562.146C 659.921,706.802 542.655,824.069 398,824.069C 253.345,824.069 136.079,706.802 136.079,562.146C 136 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLGrabCutGray() As String
            Get
                Return ResourceManager.GetString("XAMLGrabCutGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLGroundOrange&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 376.031,220.856L 274.436,322.449C 263.324,333.561 263.324,355.785 274.436,366.897L 274.436,366.897C 280.787,373.247 285.548,378.008 309.359,378.008L 333.171,3 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLGroundOrange() As String
            Get
                Return ResourceManager.GetString("XAMLGroundOrange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLExternalSet&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 376.031,220.856L 274.436,322.449C 263.324,333.561 263.324,355.785 274.436,366.897L 274.436,366.897C 280.787,373.247 285.548,378.008 309.359,378.008L 333.171,37 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLHold() As String
            Get
                Return ResourceManager.GetString("XAMLHold", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLHoldGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 376.031,220.856L 274.436,322.449C 263.324,333.561 263.324,355.785 274.436,366.897L 274.436,366.897C 280.787,373.247 285.548,378.008 309.359,378.008L 333.171,378.0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLHoldGray() As String
            Get
                Return ResourceManager.GetString("XAMLHoldGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLLeft&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 467.688,292.764L 237.513,522.937C 215.925,544.527 215.925,579.768 237.513,601.356L 467.688,831.528C 480.068,843.912 500.229,843.912 512.611,831.528L 563.091,781.049C  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLLeft() As String
            Get
                Return ResourceManager.GetString("XAMLLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLLoad&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 31.748,614.341L 634.961,614.341C 652.421,614.341 666.708,628.629 666.708,646.091L 666.708,709.587C 666.708,727.047 652.421,741.333 634.961,741.333L  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLLoadFile() As String
            Get
                Return ResourceManager.GetString("XAMLLoadFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLLoadStepActive&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 95.2441,783.049L 698.457,783.049C 715.917,783.049 730.204,797.337 730.204,814.799L 730.204,878.295C 730.204,895.755 715.917,910.041 698.45 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLLoadStepActive() As String
            Get
                Return ResourceManager.GetString("XAMLLoadStepActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLLoadStepGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF424242&quot; Geometry=&quot;F1 M 95.2441,783.049L 698.457,783.049C 715.917,783.049 730.204,797.337 730.204,814.799L 730.204,878.295C 730.204,895.755 715.917,910.041 698.457, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLLoadStepGray() As String
            Get
                Return ResourceManager.GetString("XAMLLoadStepGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLLoadStepInactive&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 95.2441,783.049L 698.457,783.049C 715.917,783.049 730.204,797.337 730.204,814.799L 730.204,878.295C 730.204,895.755 715.917,910.041 698. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLLoadStepInactive() As String
            Get
                Return ResourceManager.GetString("XAMLLoadStepInactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMain&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 278.945,243.271L 398,362.325L 517.055,243.271&quot;&gt;
        '''						&lt;GeometryDrawing.Pen&gt;
        '''							&lt;Pen Thickness=&quot;33.3333&quot; StartLineCap=&quot;Round&quot; EndLineCap=&quot;Round&quot; LineJoin=&quot;Round&quot; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMain() As String
            Get
                Return ResourceManager.GetString("XAMLMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkBackground&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF231F20&quot; Geometry=&quot;F1 M 469.552,563.736L 440.979,563.736L 440.979,441.505L 563.209,441.505L 563.209,470.079C 563.209,492.303 567.971,497.064 574.321,503.415C 585. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkBackground() As String
            Get
                Return ResourceManager.GetString("XAMLMarkBackground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkerAccuracy&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 668.805,831.672L 129.089,831.672L 129.089,291.956L 668.805,291.956M 49.72,911.041L 748.176,911.041L 748.176,212.585L 49.72,212.585L 49.72,911.041 Z &quot;&gt;
        '''				 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkerAccuracy() As String
            Get
                Return ResourceManager.GetString("XAMLMarkerAccuracy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkerGround&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 668.805,831.672L 129.089,831.672L 129.089,291.956L 668.805,291.956M 49.72,911.041L 748.176,911.041L 748.176,212.585L 49.72,212.585L 49.72,911.041 Z &quot;&gt;
        '''						 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkerGround() As String
            Get
                Return ResourceManager.GetString("XAMLMarkerGround", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkerNoise&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 645.752,645.964L 106.036,645.964L 106.036,106.248L 645.752,106.248M 26.6667,725.333L 725.123,725.333L 725.123,26.8773L 26.6667,26.8773L 26.6667,725.333 Z &quot;&gt;
        '''	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkerNoise() As String
            Get
                Return ResourceManager.GetString("XAMLMarkerNoise", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkerSave&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 668.805,831.672L 129.089,831.672L 129.089,291.956L 668.805,291.956M 49.72,911.041L 748.176,911.041L 748.176,212.585L 49.72,212.585L 49.72,911.041 Z &quot;&gt;
        '''						&lt;G [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkerSave() As String
            Get
                Return ResourceManager.GetString("XAMLMarkerSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkerScissors&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 668.805,831.672L 129.089,831.672L 129.089,291.956L 668.805,291.956M 49.72,911.041L 748.176,911.041L 748.176,212.585L 49.72,212.585L 49.72,911.041 Z &quot;&gt;
        '''				 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkerScissors() As String
            Get
                Return ResourceManager.GetString("XAMLMarkerScissors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkerStar&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 668.805,831.672L 129.089,831.672L 129.089,291.956L 668.805,291.956M 49.72,911.041L 748.176,911.041L 748.176,212.585L 49.72,212.585L 49.72,911.041 Z &quot;&gt;
        '''						&lt;G [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkerStar() As String
            Get
                Return ResourceManager.GetString("XAMLMarkerStar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkerVideo&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 668.805,831.672L 129.089,831.672L 129.089,291.956L 668.805,291.956M 49.72,911.041L 748.176,911.041L 748.176,212.585L 49.72,212.585L 49.72,911.041 Z &quot;&gt;
        '''						&lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkerVideo() As String
            Get
                Return ResourceManager.GetString("XAMLMarkerVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMarkForeground&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFFFFFF&quot; Geometry=&quot;F1 M 469.552,563.736L 440.979,563.736L 440.979,441.505L 563.209,441.505L 563.209,470.079C 563.209,492.303 567.971,497.064 574.321,503.415C 585. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMarkForeground() As String
            Get
                Return ResourceManager.GetString("XAMLMarkForeground", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLMinus&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 48.7719,562.147C 48.7719,755.809 204.337,911.376 398,911.376L 398,911.376C 591.663,911.376 747.228,755.809 747.228,562.147L 747.228,562.147C 747.228,368.485 591.663, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLMinus() As String
            Get
                Return ResourceManager.GetString("XAMLMinus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLNo&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 40.8347,562.147C 40.8347,759.404 200.743,919.312 398,919.312L 398,919.312C 595.256,919.312 755.165,759.404 755.165,562.147L 755.165,562.147C 755.165,364.891 595.256,204 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLNo() As String
            Get
                Return ResourceManager.GetString("XAMLNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLNoGrey&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 31.5013,552.815C 31.5013,750.071 191.409,909.979 388.667,909.979L 388.667,909.979C 585.923,909.979 745.832,750.071 745.832,552.815L 745.832,552.815C 745.832,355.557 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLNoGrey() As String
            Get
                Return ResourceManager.GetString("XAMLNoGrey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLPencil&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFEBEBEB&quot; Geometry=&quot;F1 M 133.739,667.961L 290.892,825.114L 54.3683,902.897L 133.739,667.961 Z &quot;/&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF0078C8&quot; Geometry=&quot;F1 M 572.749,438.1L 62 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLPencil() As String
            Get
                Return ResourceManager.GetString("XAMLPencil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLPencilOrange&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFEBEBEB&quot; Geometry=&quot;F1 M 133.739,667.961L 290.892,825.114L 54.3683,902.897L 133.739,667.961 Z &quot;/&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FFFF8737&quot; Geometry=&quot;F1 M 572.749,438 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLPencilOrange() As String
            Get
                Return ResourceManager.GetString("XAMLPencilOrange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLPlus&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 48.7719,562.147C 48.7719,755.809 204.337,911.376 398,911.376L 398,911.376C 591.663,911.376 747.228,755.809 747.228,562.147L 747.228,562.147C 747.228,368.485 591.663,2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLPlus() As String
            Get
                Return ResourceManager.GetString("XAMLPlus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLReplay&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 592.16,715.549C 771.537,826.667 762.013,642.528 901.704,715.549&quot;&gt;
        '''						&lt;GeometryDrawing.Pen&gt;
        '''							&lt;Pen Thickness=&quot;26.6667&quot; StartLineCap=&quot;Round&quot; EndLineCap=&quot;Rou [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLReplay() As String
            Get
                Return ResourceManager.GetString("XAMLReplay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLReplayGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 592.16,715.549C 771.537,826.667 762.013,642.528 901.704,715.549&quot;&gt;
        '''						&lt;GeometryDrawing.Pen&gt;
        '''							&lt;Pen Thickness=&quot;26.6667&quot; StartLineCap=&quot;Round&quot; EndLineCap= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLReplayGray() As String
            Get
                Return ResourceManager.GetString("XAMLReplayGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLRight&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 283.389,292.764L 232.911,343.245C 217.512,358.643 217.512,383.881 232.911,399.439L 395.62,562.147L 232.911,724.856C 217.512,740.413 217.512,765.652 232.911,781.049L  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLRight() As String
            Get
                Return ResourceManager.GetString("XAMLRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLSave&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 90.044,214.377C 67.82,214.377 50.3587,231.84 50.3587,254.063L 50.3587,869.976C 50.3587,892.2 67.82,909.66 90.044,909.66L 705.955,909.66C 728.179,909.66 745.64,892.2 7 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLSave() As String
            Get
                Return ResourceManager.GetString("XAMLSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLSave&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 31.748,609.008L 634.961,609.008C 652.421,609.008 666.708,623.296 666.708,640.757L 666.708,704.253C 666.708,721.713 652.421,736 634.961,736L 31.748,7 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLSaveFile() As String
            Get
                Return ResourceManager.GetString("XAMLSaveFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLSaveVideo&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF434242&quot; Geometry=&quot;F1 M 31.9147,608.841L 635.128,608.841C 652.588,608.841 666.875,623.129 666.875,640.591L 666.875,704.087C 666.875,721.547 652.588,735.833 635.128,735 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLSaveVideoActive() As String
            Get
                Return ResourceManager.GetString("XAMLSaveVideoActive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLSaveVideoInactive&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Brush=&quot;#FF008BFF&quot; Geometry=&quot;F1 M 365.927,544.688L 524.668,385.946C 532.606,378.01 540.542,370.073 540.542,354.198C 540.542,338.325 524.668,322.45 508.794,322.45L 429.42 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLSaveVideoInactive() As String
            Get
                Return ResourceManager.GetString("XAMLSaveVideoInactive", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLSitting&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 242.717,296.916C 242.717,334.944 273.547,365.777 311.581,365.777L 311.581,365.777C 349.611,365.777 380.441,334.944 380.441,296.916L 380.441,296.916C 380.441,258.88 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLSitting() As String
            Get
                Return ResourceManager.GetString("XAMLSitting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLSittingGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 242.717,296.916C 242.717,334.944 273.547,365.777 311.581,365.777L 311.581,365.777C 349.611,365.777 380.441,334.944 380.441,296.916L 380.441,296.916C 380.441,25 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLSittingGray() As String
            Get
                Return ResourceManager.GetString("XAMLSittingGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLStanding&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 321.761,394.353C 309.553,394.353 299.616,404.289 299.616,416.497L 299.616,642.572C 299.616,654.78 309.553,664.717 321.761,664.717L 329.26,664.717L 329.26,857.856C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLStanding() As String
            Get
                Return ResourceManager.GetString("XAMLStanding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLStandingGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 321.761,394.353C 309.553,394.353 299.616,404.289 299.616,416.497L 299.616,642.572C 299.616,654.78 309.553,664.717 321.761,664.717L 329.26,664.717L 329.26,857. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLStandingGray() As String
            Get
                Return ResourceManager.GetString("XAMLStandingGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLView&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 461.567,653L 626.657,854.6C 653.643,886.348 704.439,883.173 734.6,854.6L 734.6,854.6C 763.173,824.439 766.348,773.643 734.6,748.243L 533,581.567L 461.567,653 Z &quot;&gt;
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLView() As String
            Get
                Return ResourceManager.GetString("XAMLView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLViewGray&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 461.567,653L 626.657,854.6C 653.643,886.348 704.439,883.173 734.6,854.6L 734.6,854.6C 763.173,824.439 766.348,773.643 734.6,748.243L 533,581.567L 461.567,653 Z &quot;&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLViewGray() As String
            Get
                Return ResourceManager.GetString("XAMLViewGray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLYes&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 40.8347,562.147C 40.8347,759.404 200.743,919.312 398,919.312L 398,919.312C 595.256,919.312 755.165,759.404 755.165,562.147L 755.165,562.147C 755.165,364.891 595.256,20 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLYes() As String
            Get
                Return ResourceManager.GetString("XAMLYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;ResourceDictionary xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;&gt;
        '''	&lt;DrawingBrush x:Key=&quot;XAMLYesGrey&quot; Stretch=&quot;Uniform&quot;&gt;
        '''		&lt;DrawingBrush.Drawing&gt;
        '''			&lt;DrawingGroup&gt;
        '''				&lt;DrawingGroup.Children&gt;
        '''					&lt;GeometryDrawing Geometry=&quot;F1 M 40.8347,562.147C 40.8347,759.404 200.743,919.312 398,919.312L 398,919.312C 595.256,919.312 755.165,759.404 755.165,562.147L 755.165,562.147C 755.165,364.891 595.25 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property XAMLYesGrey() As String
            Get
                Return ResourceManager.GetString("XAMLYesGrey", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
